FROM maven:3-jdk-8 as builder

COPY . /app
WORKDIR /app
RUN mvn -pl mico-core package -DskipTests

FROM openjdk:8-alpine
VOLUME /tmp
COPY --from=builder /app/mico-core/target/mico-core*.jar mico.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/mico.jar"]