FROM node:8.11.2-alpine as node

COPY . /app
WORKDIR /app

RUN cd mico-admin && npm install --no-package-lock && cd ..
RUN cd mico-grapheditor && npm install --no-package-lock && cd ..

RUN cd mico-admin && npm run build lint -- --force && cd ..
RUN cd mico-grapheditor && npm run build lint -- --force && cd ..

FROM nginx:1.13.12-alpine

COPY --from=node /app/dist/mico-admin /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf