#!/bin/bash
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"shortName\": \"test-service\",  \"version\": \"1.0.0\", \"name\": \"Test Service\", \"description\": \"Test description\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"max@musterman.de\",  \"description\": \"This is a test service\",  \"dockerImageName\": \"TestImage\",  \"dockerImageUri\": \"http://...\",  \"name\": \"Test Service TWO\",  \"owner\": \"Max Musterman\",  \"shortName\": \"test-service2\",  \"vcsRoot\": \"http://....\",  \"version\": \"1.2.0\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Jan\", \"crawlingSource\": \"GITHUB\", \"description\": \"Jan's description\", \"dockerImageName\": \"Jan's Image\", \"dockerImageUri\": \"http://jansImageUri.de\", \"dockerfile\": \"Jan's Docker File\", \"externalVersion\": \"1.0.1\", \"name\": \"Jan's Repository\", \"owner\": \"Jan\", \"shortName\": \"short-name-jan\", \"version\": \"1.0.1\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Jan\", \"crawlingSource\": \"GITHUB\", \"description\": \"Jan's description\", \"dockerImageName\": \"Jan's Image\", \"dockerImageUri\": \"http://jansImageUri.de\", \"dockerfile\": \"Jan's Docker File\", \"externalVersion\": \"1.0.1\", \"name\": \"Jan's Repository\", \"owner\": \"Jan\", \"shortName\": \"short-name-jan\", \"version\": \"1.0.2\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Jan\", \"crawlingSource\": \"GITHUB\", \"description\": \"Jan's description\", \"dockerImageName\": \"Jan's Image\", \"dockerImageUri\": \"http://jansImageUri.de\", \"dockerfile\": \"Jan's Docker File\", \"externalVersion\": \"1.0.1\", \"name\": \"Jan's Repository\", \"owner\": \"Jan\", \"shortName\": \"short-name-jan\", \"version\": \"2.3.1\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Pascal\", \"crawlingSource\": \"GITHUB\", \"description\": \"Pascal's description\", \"dockerImageName\": \"Pascal's Image\", \"dockerImageUri\": \"http://pascalsImageUri.de\", \"dockerfile\": \"Pascal's Docker File\", \"externalVersion\": \"3.9.0\", \"name\": \"Pascal's Repository\", \"owner\": \"Pascal\", \"shortName\": \"short-name-pascal\", \"version\": \"2.0.1\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Pascal\", \"crawlingSource\": \"GITHUB\", \"description\": \"Pascal's description\", \"dockerImageName\": \"Pascal's Image\", \"dockerImageUri\": \"http://pascalsImageUri.de\", \"dockerfile\": \"Pascal's Docker File\", \"externalVersion\": \"3.9.0\", \"name\": \"Pascal's Repository\", \"owner\": \"Pascal\", \"shortName\": \"short-name-pascal\", \"version\": \"5.1.1\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"David\", \"crawlingSource\": \"GITHUB\", \"description\": \"David's description\", \"dockerImageName\": \"DavidImage\", \"dockerImageUri\": \"http://davidsImageUri.de\", \"dockerfile\": \"David's Docker File\", \"externalVersion\": \"8.0.2\", \"name\": \"David's Repository\", \"owner\": \"Mum\", \"shortName\": \"short-name-david\", \"version\": \"4.2.3\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Fabian\", \"crawlingSource\": \"GITHUB\", \"description\": \"Fabian's description\", \"dockerImageName\": \"Fabian Image\", \"dockerImageUri\": \"http://FabiansImageUri.de\", \"dockerfile\": \"Dockerfile\", \"externalVersion\": \"4.0.2\", \"name\": \"Fabian's Repository\", \"owner\": \"Fabian\", \"shortName\": \"short-name-fabian\", \"version\": \"1.2.6\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Fabian\", \"crawlingSource\": \"GITHUB\", \"description\": \"Fabian's description\", \"dockerImageName\": \"Fabian Image\", \"dockerImageUri\": \"http://FabiansImageUri.de\", \"dockerfile\": \"Dockerfile\", \"externalVersion\": \"4.0.2\", \"name\": \"Fabian's Repository\", \"owner\": \"Fabian\", \"shortName\": \"short-name-fabian\", \"version\": \"8.2.4\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Dominik\", \"crawlingSource\": \"GITHUB\", \"description\": \"Dominik's description\", \"dockerImageName\": \"Dominik Image\", \"dockerImageUri\": \"http://Dominik sImageUri.de\", \"dockerfile\": \"Dockerfile\", \"externalVersion\": \"9.4.0\", \"name\": \"Dominik's Repository\", \"owner\": \"Dominik\", \"shortName\": \"short-name-dominik\", \"version\": \"5.6.1\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"Dude\", \"crawlingSource\": \"GITHUB\", \"description\": \"Dude's description\", \"dockerImageName\": \"Dude Image\", \"dockerImageUri\": \"http://DudeImageUri.de\", \"dockerfile\": \"Dockerfile\", \"externalVersion\": \"1.0.0\", \"name\": \"Dude's Repository\", \"owner\": \"Dude\", \"shortName\": \"short-name-dude\", \"version\": \"0.5.6\"}"

curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-jan/1.0.1/dependees/short-name-pascal/2.0.1" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-jan/1.0.1/dependees/short-name-dude/0.5.6" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-pascal/2.0.1/dependees/short-name-dude/0.5.6" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-dominik/5.6.1/dependees/short-name-fabian/1.2.6" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-dominik/5.6.1/dependees/short-name-jan/1.0.1" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-david/4.2.3/dependees/short-name-jan/1.0.1" -H "accept: application/hal+json" -H "Content-Type: application/json"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/services/short-name-david/4.2.3/dependees/short-name-fabian/1.2.6" -H "accept: application/hal+json" -H "Content-Type: application/json"

curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/applications" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"string\", \"description\": \"Some Application Description\", \"name\": \"SomeApplication\", \"owner\": \"SomeGuy\", \"shortName\": \"some-application-short-name\", \"version\": \"1.0.0\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/applications" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"IT\", \"description\": \"Some Application Description\", \"name\": \"SomeApplication\", \"owner\": \"SomeGuy\", \"shortName\": \"some-really-cool-application-short-name\", \"version\": \"1.3.3-pre7\"}"
curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/applications" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{ \"contact\": \"dude\", \"description\": \"Some Dudes Application Description\", \"name\": \"SomeDudesApplication\", \"owner\": \"SomeDude\", \"shortName\": \"some-dudes-application-short-name\", \"version\": \"7.0.1\"}"

curl --styled-output --silent --show-error --fail -o /dev/null -w 'POST %{url_effective}\t Response: %{http_code}\n' -X POST "http://localhost:8080/applications/some-application-short-name/1.0.0/services/short-name-david/4.2.3" -H "accept: application/hal+json" -H "Content-Type: application/json"

